# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pokes', models.ManyToManyField(to='pokeapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='pokes',
        ),
        migrations.AddField(
            model_name='history',
            name='pokes',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
