# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0003_auto_20170130_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
