# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0005_remove_poke_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='pokecount',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
