# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0006_poke_pokecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='pokecount',
            field=models.CharField(max_length=255),
        ),
    ]
