# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0008_auto_20170130_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='pokecount',
        ),
    ]
