# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0009_remove_poke_pokecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='pokecount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
