# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0012_auto_20170130_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whopoke',
            old_name='gotpoke',
            new_name='pokeby',
        ),
    ]
