# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0013_auto_20170130_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='gotpoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gotpoke_name', models.CharField(max_length=255)),
                ('pokecount', models.IntegerField()),
                ('pokeby', models.ManyToManyField(to='pokeapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='whopoke',
            name='whopoke',
        ),
        migrations.DeleteModel(
            name='whopoke',
        ),
    ]
