# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0018_auto_20170131_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('poke_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokeapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='gotpoke',
            name='pokeby',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='pokeothertotal',
            new_name='PokeHistory',
        ),
        migrations.DeleteModel(
            name='gotpoke',
        ),
    ]
