# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0019_auto_20170131_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='poke_by',
            new_name='user',
        ),
    ]
