# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0020_auto_20170131_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='name',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='user',
        ),
        migrations.AddField(
            model_name='poke',
            name='beingpoke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beingpoke', to='pokeapp.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='pokeby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokeby', to='pokeapp.User'),
        ),
    ]
