# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0023_auto_20170131_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='pokedby',
        ),
        migrations.AddField(
            model_name='poke',
            name='receivedpoke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivedpoke', to='pokeapp.User'),
        ),
        migrations.AlterField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='pokeapp.User'),
        ),
    ]
